name: SR_FLUTTER_FE_PROD

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"
    
jobs:
  pull-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        run: |
          git clone https://sarva-suvidhaen:${{ secrets.PERSONAL_TOKEN  }}@github.com/s2pl/SwachhStations_FE_Flutter.git

      - name: Add source repository as upstream
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          cd SwachhStations_FE_Flutter
          git remote add upstream https://sarva-suvidhaen:${{ secrets.PERSONAL_TOKEN  }}@github.com/sarva-suvidhaen/SwachhStations_FE_Flutter.git

      - name: Push to destination repository
        run: |
          cd SwachhStations_FE_Flutter
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git rm -rf --cached .github/workflows/
          git commit --amend --no-edit
          git push -f upstream main

      

          
